services:
  app:
    build: .
    container_name: dash_app
    ports:
      - "8050:8050"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: previsao_climatica
    command: ["python", "app.py"]  # 🔹 Adiciona comando para rodar o Dash
  
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: previsao_climatica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
